# Generated by Django 6.1 on 2026-08-17 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='food_photos/')),
                ('serving_size', models.FloatField()),
                ('serving_unit', models.CharField(max_length=20)),
                ('calories', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('sugar_g', models.FloatField(blank=True, null=True)),
                ('sodium_mg', models.FloatField(blank=True, null=True)),
                ('micros_json', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('photo_pending_ai', 'Photo Pending Ai'), ('ai_processed', 'Ai Processed')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
